# Generated by Django 4.2.4 on 2023-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
